language: node_js
node_js:
- '7'
cache:
  directories:
  - node_modules
env:
  global:
    secure: UxRFMXIdHvNMgaesL13CzGYTDTxTb7Z+ApGO/aLT4AM7HSvnfkio1u07DOUe+S2DECoh0LPwA58QfsjLuqTux0Wbr0dSgN7JIfzjuRMfbbHOfWoYTkX324OkCQUVo49Xawov7R92iNAftku0YlXr+gKL6Yq3t1FhvTArxrqmBFwxMonJVhQ2v51Ul88i5e2s95H9AXX0Zs+Lxm4cC3EJLpXcwftiDVdtyXK6JCaJNk9q0Uf+UoVgrcu4W7jHMkOrulsDEnY+ILy/GztsDfWYVfsCR77uoK60PpZbi1cFX/1OjX0zPPVz5qSJaDWAfOos7LZ1Sno3ujv3ybCZdiVe09olR6/kH9iYSodJXuDfIqNzj/EAU3fKqdbcqTaKPzbB78eRrQKeg9+bv1SBkGeZOkf37+G0UJ607E/80cVq9HvejJPLrCW0vVhyXbGNphs7HK5JOzEdLHYpW8l6D5uL2kLc64eoLwLs2oYZxyMWhDSbD4IGC+BX6C4XGZ0xRMs6+sxoas29fvszc81Jr/T7aeRJZBU/MVEyFn5ZeURY5BK+3IsFK8fDmRulfTX/Szx2CcostMxMtiQ0Bn9xa+Ba6xTlvkKLP4RNJcuzr43gQTOTLXgc0LnYRcQ7Vbrb0SVjUGqeNwkXvJ7KFj93GlF4HrpSyyDcl18Nu8x8x2nQmbk=
