language: node_js
node_js:
- '7'

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure : change

cache:
  directories:
  - node_modules

env:
  - NODE_ENV=PROD

install:
  - npm install

script:
  - npm run build

deploy:
  - provider: firebase
    token:
      secure: UxRFMXIdHvNMgaesL13CzGYTDTxTb7Z+ApGO/aLT4AM7HSvnfkio1u07DOUe+S2DECoh0LPwA58QfsjLuqTux0Wbr0dSgN7JIfzjuRMfbbHOfWoYTkX324OkCQUVo49Xawov7R92iNAftku0YlXr+gKL6Yq3t1FhvTArxrqmBFwxMonJVhQ2v51Ul88i5e2s95H9AXX0Zs+Lxm4cC3EJLpXcwftiDVdtyXK6JCaJNk9q0Uf+UoVgrcu4W7jHMkOrulsDEnY+ILy/GztsDfWYVfsCR77uoK60PpZbi1cFX/1OjX0zPPVz5qSJaDWAfOos7LZ1Sno3ujv3ybCZdiVe09olR6/kH9iYSodJXuDfIqNzj/EAU3fKqdbcqTaKPzbB78eRrQKeg9+bv1SBkGeZOkf37+G0UJ607E/80cVq9HvejJPLrCW0vVhyXbGNphs7HK5JOzEdLHYpW8l6D5uL2kLc64eoLwLs2oYZxyMWhDSbD4IGC+BX6C4XGZ0xRMs6+sxoas29fvszc81Jr/T7aeRJZBU/MVEyFn5ZeURY5BK+3IsFK8fDmRulfTX/Szx2CcostMxMtiQ0Bn9xa+Ba6xTlvkKLP4RNJcuzr43gQTOTLXgc0LnYRcQ7Vbrb0SVjUGqeNwkXvJ7KFj93GlF4HrpSyyDcl18Nu8x8x2nQmbk=
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: CnXs1SqJi9C4sbhxC/PVk5KA914GwQRyEmI7ae1ZBVBl5B5bsPw6twkyQ+MEYDDiNi8ZAxKdh6hDA5fAKLS0xCRxq1TPAn6MfDepIf5kqEUqCRIA7wO7Md7wdPSzK+0G39UaNqvVKDLKuUXFQdkcew3y5PVjcXqj6T3oxkt/JUdSlTg8qInn8xLHKE3UdDH4iSRZUz+yGBT0k0cPsf+5MW2qm6lOrUivLtmIHB/5wRKfKQnUgofHzSebghO0zXySvYUiuwM1Ds2nZ6KRMm2ypxtefsSPakQ5AICo3O/FP61s+HDNIMsTLV79L8qfkH4SRMuIepO3ISbT94qjPhTYfoNAFFzFLa1d1PX+MrzDAdIHBTIdABgfUxdFVJ7Q72KfRpy42d11fAYz73fn876TeDw9CwFLphMnwLKNR3f+PlJU56kbFgi/QLZvBu2MiDo4m4Cfh48y0vBWURI9wTeeFVfyliXngp9O5spMBKiUnYldo3VGny1V5W7TMIgrkmvEDH/S8eqrpLbR9020EvJii/QUvKgQL6XThFJj2UU3enrRZtQw7/MVB+j0n66RU53mQNfIID4zVKz9movkEaMHG2N6L+ljbg753zsHs6wyEwZncjEJeLpaY2FwRjtXSOMRTdsfbibUdrq3/laH9uDkBqeulWl/Z8znoMCTzDH71zc=
    file_glob: true
    file: public/*
    skip_cleanup: true
    tag: next
